#!/usr/bin/env tsx

import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { buildAnthropicModels } from "./sources/anthropic.js";
import { buildCodexModels } from "./sources/codex.js";
import { buildOpenCodeGoModels } from "./sources/opencode-go.js";
import type { ModelsDevApi } from "./shared.js";
import type { Model } from "../src/types.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const packageRoot = join(__dirname, "..");

async function fetchModelsDevCatalog(): Promise<ModelsDevApi> {
	console.log("Fetching models from models.dev API...");
	const response = await fetch("https://models.dev/api.json");
	if (!response.ok) throw new Error(`models.dev API returned ${response.status} ${response.statusText}`);
	return (await response.json()) as ModelsDevApi;
}

async function generateModels() {
	const catalog = await fetchModelsDevCatalog();
	const allModels = buildAnthropicModels(catalog);
	allModels.push(...buildCodexModels(catalog));
	allModels.push(...buildOpenCodeGoModels(catalog));

	const providers: Record<string, Record<string, Model<any>>> = {};
	for (const model of allModels) {
		if (!providers[model.provider]) {
			providers[model.provider] = {};
		}
		if (!providers[model.provider][model.id]) {
			providers[model.provider][model.id] = model;
		}
	}

	let output = `// This file is auto-generated by scripts/generate.ts
// Do not edit manually - run 'just generate-models' to update

import type { Model } from "./types.js";

export const MODELS = {
`;

	const sortedProviderIds = Object.keys(providers).sort();
	for (const providerId of sortedProviderIds) {
		const models = providers[providerId];
		output += `\t${JSON.stringify(providerId)}: {\n`;

		const sortedModelIds = Object.keys(models).sort();
		for (const modelId of sortedModelIds) {
			const model = models[modelId];
			output += `\t\t"${model.id}": {\n`;
			output += `\t\t\tid: "${model.id}",\n`;
			output += `\t\t\tname: "${model.name}",\n`;
			output += `\t\t\tapi: "${model.api}",\n`;
			output += `\t\t\tprovider: "${model.provider}",\n`;
			if (model.baseUrl !== undefined) {
				output += `\t\t\tbaseUrl: "${model.baseUrl}",\n`;
			}
			if (model.headers) {
				output += `\t\t\theaders: ${JSON.stringify(model.headers)},\n`;
			}
			if (model.compat) {
				output += `			compat: ${JSON.stringify(model.compat)},
`;
			}
			output += `\t\t\treasoning: ${model.reasoning},\n`;
			output += `\t\t\tinput: [${model.input.map(i => `"${i}"`).join(", ")}],\n`;
			output += `\t\t\tcost: {\n`;
			output += `\t\t\t\tinput: ${model.cost.input},\n`;
			output += `\t\t\t\toutput: ${model.cost.output},\n`;
			output += `\t\t\t\tcacheRead: ${model.cost.cacheRead},\n`;
			output += `\t\t\t\tcacheWrite: ${model.cost.cacheWrite},\n`;
			if (model.cost.tiers?.length) {
				output += `\t\t\t\ttiers: [\n`;
				for (const tier of model.cost.tiers) {
					output += `\t\t\t\t\t{\n`;
					output += `\t\t\t\t\t\tinputTokensAbove: ${tier.inputTokensAbove},\n`;
					output += `\t\t\t\t\t\tinput: ${tier.input},\n`;
					output += `\t\t\t\t\t\toutput: ${tier.output},\n`;
					output += `\t\t\t\t\t\tcacheRead: ${tier.cacheRead},\n`;
					output += `\t\t\t\t\t\tcacheWrite: ${tier.cacheWrite},\n`;
					output += `\t\t\t\t\t},\n`;
				}
				output += `\t\t\t\t],\n`;
			}
			output += `\t\t\t},\n`;
			output += `\t\t\tcontextWindow: ${model.contextWindow},\n`;
			output += `\t\t\tmaxTokens: ${model.maxTokens},\n`;
			if (model.thinkingLevelMap) {
				output += `\t\t\tthinkingLevelMap: ${JSON.stringify(model.thinkingLevelMap)},\n`;
			}
			if (model.thinkingMode !== undefined) {
				output += `\t\t\tthinkingMode: "${model.thinkingMode}",\n`;
			}
			if (model.supportsTemperature !== undefined) {
				output += `\t\t\tsupportsTemperature: ${model.supportsTemperature},\n`;
			}
			if (model.supportsThinkingDisabled !== undefined) {
				output += `\t\t\tsupportsThinkingDisabled: ${model.supportsThinkingDisabled},\n`;
			}
			output += `\t\t} satisfies Model<"${model.api}">,\n`;
		}

		output += `\t},\n`;
	}

	output += `} as const;
`;

	writeFileSync(join(packageRoot, "src/models.generated.ts"), output);
	console.log("Generated src/models.generated.ts");

	const totalModels = allModels.length;
	const reasoningModels = allModels.filter(m => m.reasoning).length;

	console.log(`Tool-capable models: ${totalModels}`);
	console.log(`Reasoning-capable models: ${reasoningModels}`);

	for (const [provider, models] of Object.entries(providers)) {
		console.log(`${provider}: ${Object.keys(models).length} models`);
	}
}

generateModels().catch(error => {
	console.error(error);
	process.exitCode = 1;
});
